### ISSUE TITLE
Add API doc for CI server endpoints

### ISSUE THREAD

**Issue by mdinler** [DD2480-G12/a2-ci-server#33]
There are three endpoints:
- POST /push-events
- GET /history
- GET /history/{id}

**Comment by mdinler** [comment]
Please describe the status codes returned and the response body for each endpoint.

**Comment by spelgubbe** [comment]
### POST /push-events:
204 (no content) always.
### GET /history:
200 (ok) always. (if history is empty then it returns an empty array)
### GET /history/{id}:
400 (bad request) if id is not a number
404 (not found) if build id doesn't exist
else 200 (ok)
